a = input('Escreve algo:')
print('O tipo primitivo desse valor é', type (a))
print('Só tem espaço?',a.isspace())
print('É só número?',a.isnumeric ())
print('É alfabetico?', a.isalpha())
print('É alfanumerico?',a.isalnum())
print('Está em maiúscula?',a.isupper())
print('Está em miniscula?',a.islower())
print('Está capitalizada?',a.istitle())
